Standalone PR test - Ignore me
pavel-mikula-sonarsource/GitHubActionPlayground pull request #3
Opened 2020-10-16 15:08 UTC by pavel-mikula-sonarsource

2020-12-01 13:18 UTC, PavlinII requested changes
Test

2020-12-01 14:10 UTC, PavlinII requested changes
Moc prázdné

2020-12-01 14:41 UTC, PavlinII reviewed
Comment

2020-12-01 14:42 UTC, PavlinII requested changes
Too long

2020-12-01 14:53 UTC, PavlinII reviewed
Comment

2020-12-01 14:55 UTC, PavlinII requested changes
changes

2020-12-01 15:05 UTC, PavlinII requested changes
xxx

2020-12-01 15:12 UTC, PavlinII requested changes
xxx

2020-12-01 15:33 UTC, PavlinII requested changes
rq

2020-12-01 15:34 UTC, PavlinII requested changes
rq

2020-12-02 11:07 UTC, PavlinII reviewed
c

2020-12-02 15:42 UTC, andrei-epure-sonarsource approved these changes

2020-12-03 10:29 UTC, PavlinII approved these changes
OK

2021-01-29 13:37 UTC, merged